### ISSUE TITLE
How to enable brands

### ISSUE THREAD

**Issue by mooror** [DoggersHusky/silverstripe-fa-picker#20]
This may seem like a silly question, but with the free version of font-awesome I cannot for the life of me get the brand icons to display.

When I used this module with font awesome 5 I was able to get them to display but not with version 6 and that is with me trying to use the default set and trying to use 6.5.1 with the following config:

```yaml
FontawesomeIcons:
  icon_yml_location: 'app/fontawesome/icon-families.yml'
  free_css_cdn_version: '6.5.1'
```
![Screenshot 2024-03-26 at 20-36-36 Silverstripe - Edit Page](https://github.com/DoggersHusky/silverstripe-fa-picker/assets/6110819/15a66b2e-2c95-4ee2-a958-8b640c21dcf7)
